# Use Customer_Segmentation Notebook Template

In [1]:
import numpy as np # linear algebra
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

Matplotlib created a temporary cache directory at /tmp/matplotlib-krlvcvm7 because the default path (/home/mosaic-ai/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


# Read the intermeditary output of K-Means clustering Model Building Notebooks for model training and registration

In [2]:
df = pd.read_csv('/data/Output/kmeans_clustered_customer_Data.csv')

In [3]:
df.shape

(122882, 29)

In [4]:
df.tail()

CUSTOMER_ID        DATE  AGE     SEX  \
122877  3a7ce3d5-0f4b-4575-badc-3553f5440c92  2023-05-01   32    MALE   
122878  e2a8f308-57eb-4f55-bc13-399378f246d3  2022-12-01   27    MALE   
122879  599c0e61-9bbc-4e14-bbfd-b07f5a398669  2022-12-01   33  FEMALE   
122880  77298902-f899-4c3e-9104-06d1736fb089  2023-06-01   33  FEMALE   
122881  cd75294e-c31f-41b3-b78c-1d3e7322ddcf  2022-12-01   44  FEMALE   

       EDUCATION_LEVEL EMPLOYMENT_STATUS      HOBBIES MARITAL_STATUS  \
122877     High School        Unemployed      reading         Single   
122878             PhD        Unemployed      camping         Single   
122879     High School        Unemployed  video-games         Single   
122880         College        Unemployed   basketball         Single   
122881     High School          Employed     exercise        Married   

            DEPENDENTS REGISTRATION_DATE  ... INSTALLMENTS_PURCHASES  \
122877   One Dependent        2020-03-12  ...              339.07230   
122878   One Dependent        2009-05-12  ...              482.58685   
122879   One Dependent        2007-02-12  ...                0.00000   
122880   One Dependent        2001-02-12  ...                0.00000   
122881  Two Dependents        2001-02-12  ...                0.00000   

        PURCHASES_FREQUENCY ONEOFF_PURCHASES_FREQUENCY  \
122877            Very high                        Low   
122878            Very high                   Very low   
122879             Very low                   Very low   
122880             Very low                   Very low   
122881             Very low                   Very low   

        PURCHASES_INSTALLMENTS_FREQUENCY  PURCHASES_TRX     PAYMENTS  \
122877                         Very high          21.20   273.352691   
122878                         Very high          25.92   474.722440   
122879                          Very low           0.00   568.542708   
122880                          Very low           0.00   517.588408   
122881                          Very low           0.00  1029.696570   

        MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  Cluster           Cluster_Type  
122877        242.288921               0.0        0  Conservative Spenders  
122878        165.534652               0.0        0  Conservative Spenders  
122879        549.300475               0.0        0  Conservative Spenders  
122880        544.214360               0.0        0  Conservative Spenders  
122881       1552.899035               0.0        2     Cash Advance Users  

[5 rows x 29 columns]

In [5]:
to_drop = ['CUSTOMER_ID','DATE','AGE','SEX','EDUCATION_LEVEL','EMPLOYMENT_STATUS','HOBBIES','MARITAL_STATUS','BANK_ACCOUNT_TYPE',
 'DEPENDENTS','REGISTRATION_DATE','PURCHASES_FREQUENCY','ONEOFF_PURCHASES_FREQUENCY','PURCHASES_INSTALLMENTS_FREQUENCY','BALANCE_FREQUENCY','Cluster_Type']

In [6]:
df.drop(to_drop, axis= 1, inplace= True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122882 entries, 0 to 122881
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   BALANCE                 122882 non-null  float64
 1   CREDIT_LIMIT            122882 non-null  float64
 2   CASH_ADVANCE            122882 non-null  float64
 3   CASH_ADVANCE_FREQUENCY  122882 non-null  float64
 4   CASH_ADVANCE_TRX        122882 non-null  float64
 5   PURCHASES               122882 non-null  float64
 6   ONEOFF_PURCHASES        122882 non-null  float64
 7   INSTALLMENTS_PURCHASES  122882 non-null  float64
 8   PURCHASES_TRX           122882 non-null  float64
 9   PAYMENTS                122882 non-null  float64
 10  MINIMUM_PAYMENTS        122882 non-null  float64
 11  PRC_FULL_PAYMENT        122882 non-null  float64
 12  Cluster                 122882 non-null  int64  
dtypes: float64(12), int64(1)
memory usage: 12.2 MB


In [8]:
X = df.drop(['Cluster'],axis = 1 )
y = df[['Cluster']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state = 101)

In [9]:
X_train.shape, X_test.shape

((86017, 12), (36865, 12))

# Decision Tree Classifier

In [10]:
#Training our algorithm
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
clf_prediction = clf.predict(X_test)

In [11]:
#Checking our prediction accuracy score
print(confusion_matrix(y_test, clf_prediction))

[[25618     0   138   108]
 [    0   309     0    12]
 [  113     0  5936    14]
 [  157     8    18  4434]]


In [12]:
print(classification_report(y_test, clf_prediction))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     25864
           1       0.97      0.96      0.97       321
           2       0.97      0.98      0.98      6063
           3       0.97      0.96      0.97      4617

    accuracy                           0.98     36865
   macro avg       0.98      0.97      0.98     36865
weighted avg       0.98      0.98      0.98     36865



In [13]:
clf.feature_importances_

array([0.07953907, 0.03899043, 0.28756276, 0.03309394, 0.10493316,
       0.34302369, 0.0058551 , 0.01402622, 0.04115779, 0.02551205,
       0.01339014, 0.01291564])

In [14]:
pd.Series(clf.feature_importances_,index=X_train.columns).sort_values(ascending=False)

PURCHASES                 0.343024
CASH_ADVANCE              0.287563
CASH_ADVANCE_TRX          0.104933
BALANCE                   0.079539
PURCHASES_TRX             0.041158
CREDIT_LIMIT              0.038990
CASH_ADVANCE_FREQUENCY    0.033094
PAYMENTS                  0.025512
INSTALLMENTS_PURCHASES    0.014026
MINIMUM_PAYMENTS          0.013390
PRC_FULL_PAYMENT          0.012916
ONEOFF_PURCHASES          0.005855
dtype: float64

## We achieve 98% accuracy at predicting potiential new customers behavior

In [15]:
from fosforml import *
from fosforml.constants import MLModelFlavours
import requests

In [16]:
payload_dict = X_train.iloc[0].to_dict()

In [17]:
payload_dict

{'BALANCE': 2378.1156415200003,
 'CREDIT_LIMIT': 5640.0,
 'CASH_ADVANCE': 306.9114516,
 'CASH_ADVANCE_FREQUENCY': 0.08749965,
 'CASH_ADVANCE_TRX': 1.035,
 'PURCHASES': 2515.24,
 'ONEOFF_PURCHASES': 2719.5,
 'INSTALLMENTS_PURCHASES': 184.44,
 'PURCHASES_TRX': 9.81,
 'PAYMENTS': 674.70383367,
 'MINIMUM_PAYMENTS': 736.03712752,
 'PRC_FULL_PAYMENT': 0.0}

# Sample Model Payload

In [18]:
print ('{ "payload": ', payload_dict, "}")

{ "payload":  {'BALANCE': 2378.1156415200003, 'CREDIT_LIMIT': 5640.0, 'CASH_ADVANCE': 306.9114516, 'CASH_ADVANCE_FREQUENCY': 0.08749965, 'CASH_ADVANCE_TRX': 1.035, 'PURCHASES': 2515.24, 'ONEOFF_PURCHASES': 2719.5, 'INSTALLMENTS_PURCHASES': 184.44, 'PURCHASES_TRX': 9.81, 'PAYMENTS': 674.70383367, 'MINIMUM_PAYMENTS': 736.03712752, 'PRC_FULL_PAYMENT': 0.0} }


# Define a Score function

In [37]:
@scoring_func
def score(model, request):
    payload_dict = request.json["payload"]
    df = pd.DataFrame(payload_dict, index=[0])
    output = model.predict(df)
    
    if output == 0:
        return 'Conservative Spenders'
    elif output == 1:
        return 'High Spender Users'
    elif output == 2:
        return 'Cash Advance Users'
    else:
        return 'Active Credit Users'

# Sample Model Inference JSON Request

In [38]:
payload_dict

{'BALANCE': 2378.1156415200003,
 'CREDIT_LIMIT': 5640.0,
 'CASH_ADVANCE': 306.9114516,
 'CASH_ADVANCE_FREQUENCY': 0.08749965,
 'CASH_ADVANCE_TRX': 1.035,
 'PURCHASES': 2515.24,
 'ONEOFF_PURCHASES': 2719.5,
 'INSTALLMENTS_PURCHASES': 184.44,
 'PURCHASES_TRX': 9.81,
 'PAYMENTS': 674.70383367,
 'MINIMUM_PAYMENTS': 736.03712752,
 'PRC_FULL_PAYMENT': 0.0}

In [39]:
req.json = {"payload":payload_dict}

In [40]:
req.json

{'payload': {'BALANCE': 2378.1156415200003,
  'CREDIT_LIMIT': 5640.0,
  'CASH_ADVANCE': 306.9114516,
  'CASH_ADVANCE_FREQUENCY': 0.08749965,
  'CASH_ADVANCE_TRX': 1.035,
  'PURCHASES': 2515.24,
  'ONEOFF_PURCHASES': 2719.5,
  'INSTALLMENTS_PURCHASES': 184.44,
  'PURCHASES_TRX': 9.81,
  'PAYMENTS': 674.70383367,
  'MINIMUM_PAYMENTS': 736.03712752,
  'PRC_FULL_PAYMENT': 0.0}}

In [41]:
pd.DataFrame(payload_dict, index=[0])

BALANCE  CREDIT_LIMIT  CASH_ADVANCE  CASH_ADVANCE_FREQUENCY  \
0  2378.115642        5640.0    306.911452                  0.0875   

   CASH_ADVANCE_TRX  PURCHASES  ONEOFF_PURCHASES  INSTALLMENTS_PURCHASES  \
0             1.035    2515.24            2719.5                  184.44   

   PURCHASES_TRX    PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  
0           9.81  674.703834        736.037128               0.0

In [23]:
payload_dict = X_train.iloc[0].to_dict()
payload_dict

{'BALANCE': 2378.1156415200003,
 'CREDIT_LIMIT': 5640.0,
 'CASH_ADVANCE': 306.9114516,
 'CASH_ADVANCE_FREQUENCY': 0.08749965,
 'CASH_ADVANCE_TRX': 1.035,
 'PURCHASES': 2515.24,
 'ONEOFF_PURCHASES': 2719.5,
 'INSTALLMENTS_PURCHASES': 184.44,
 'PURCHASES_TRX': 9.81,
 'PAYMENTS': 674.70383367,
 'MINIMUM_PAYMENTS': 736.03712752,
 'PRC_FULL_PAYMENT': 0.0}

In [42]:
req = requests.Request()
req.json = {"payload":payload_dict}
#req.json = {"payload":payload}
y_req = req
score(clf, y_req)

'Conservative Spenders'

In [43]:
payload_dict = X_train.iloc[1000].to_dict()
payload_dict

{'BALANCE': 2161.67703016,
 'CREDIT_LIMIT': 2760.0,
 'CASH_ADVANCE': 7399.04709474,
 'CASH_ADVANCE_FREQUENCY': 0.35999964,
 'CASH_ADVANCE_TRX': 8.64,
 'PURCHASES': 0.0,
 'ONEOFF_PURCHASES': 0.0,
 'INSTALLMENTS_PURCHASES': 0.0,
 'PURCHASES_TRX': 0.0,
 'PAYMENTS': 7500.34928286,
 'MINIMUM_PAYMENTS': 839.24561325,
 'PRC_FULL_PAYMENT': 0.17666702}

In [44]:
req = requests.Request()
req.json = {"payload":payload_dict}
#req.json = {"payload":payload}
y_req = req
score(clf, y_req)

'Cash Advance Users'

# Model registration Code

In [45]:
## registering the model in Fosfor.
model_reg = register_model(clf,
               score, 
               name="Customer_Segmentation_Dtree_Cluster_Classifier", 
               description="Customer_Segmentation_Dtree_Cluster_Classifier",
               flavour=MLModelFlavours.sklearn,
               model_type="classification",
               init_script="\\n pip install fosforml \\n pip install fosforio[snowflake] \\n pip install seaborn \\n pip install snowflake-connector-python[pandas]",
               y_true=y_test,
               y_pred=clf_prediction,
               prob=clf_prediction,
               features=X_train.columns,
               input_type="json", 
               explain_ai=True,
               x_train=X_train, 
               x_test=X_test, 
               y_train=y_train,
               y_test=y_test,
               feature_names=X_train.columns.tolist(),
               original_features=X_train.columns.tolist(),
               feature_ids=X_train.columns,
               kyd=True, kyd_score = True)

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


# Another Version

In [46]:
clf_prediction = clf.predict(X_train)

In [47]:
## registering the model in Fosfor.
model_reg = register_model(clf,
               score, 
               name="Customer_Segmentation_Dtree_Cluster_Classifier", 
               description="Customer_Segmentation_Dtree_Cluster_Classifier",
               flavour=MLModelFlavours.sklearn,
               model_type="classification",
               init_script="\\n pip install fosforml \\n pip install fosforio[snowflake] \\n pip install seaborn \\n pip install snowflake-connector-python[pandas]",
               y_true=y_train,
               y_pred=clf_prediction,
               prob=clf_prediction,
               features=X_train.columns,
               input_type="json", 
               explain_ai=True,
               x_train=X_test, 
               x_test=X_train, 
               y_train=y_test,
               y_test=y_train,
               feature_names=X_train.columns.tolist(),
               original_features=X_train.columns.tolist(),
               feature_ids=X_train.columns,
               kyd=True, kyd_score = True)

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


# Write back the output to Snowflake

In [49]:
df = pd.read_csv('/data/Output/kmeans_clustered_customer_Data.csv')

In [52]:
df.head()

CUSTOMER_ID        DATE  AGE     SEX  \
0  PNC32940ed8-682f-4052-92b2-cfdc7f41e  2023-12-01   49  FEMALE   
1  PNCe415caf5-6212-4f50-a062-c12bf1eea  2024-01-01   34    MALE   
2  PNC1ef5b665-11ae-40d7-b364-be8fa02b9  2023-02-01   34    MALE   
3  PNC436a6069-0e61-47f2-96e8-d11c19e4b  2024-04-01   29    MALE   
4  PNCaaa1c8bb-7289-4c25-a05e-efe26e316  2024-02-01   29    MALE   

  EDUCATION_LEVEL EMPLOYMENT_STATUS      HOBBIES MARITAL_STATUS  \
0     Undisclosed          Employed  Undisclosed        Married   
1     Undisclosed        Unemployed  Undisclosed        Married   
2     Undisclosed        Unemployed  Undisclosed        Married   
3     Undisclosed        Unemployed  Undisclosed         Single   
4     Undisclosed        Unemployed  Undisclosed         Single   

       DEPENDENTS REGISTRATION_DATE  ... INSTALLMENTS_PURCHASES  \
0  Two Dependents        2004-11-12  ...                    0.0   
1   No Dependents        2023-07-12  ...                    0.0   
2   No Dependents        2021-11-12  ...                    0.0   
3   One Dependent        2019-07-12  ...                    0.0   
4   One Dependent        2022-09-12  ...                    0.0   

   PURCHASES_FREQUENCY ONEOFF_PURCHASES_FREQUENCY  \
0             Very low                   Very low   
1            Very high                  Very high   
2            Very high                  Very high   
3             Very low                   Very low   
4             Very low                   Very low   

   PURCHASES_INSTALLMENTS_FREQUENCY  PURCHASES_TRX     PAYMENTS  \
0                          Very low          0.000  3774.789989   
1                          Very low         11.400   665.611414   
2                          Very low         10.920   653.170079   
3                          Very low          0.965     0.000000   
4                          Very low          1.060     0.000000   

   MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  Cluster           Cluster_Type  
0       1007.999804          0.214444        2     Cash Advance Users  
1        589.647700          0.000000        0  Conservative Spenders  
2        570.829156          0.000000        0  Conservative Spenders  
3          0.000000          0.000000        0  Conservative Spenders  
4          0.000000          0.000000        0  Conservative Spenders  

[5 rows x 29 columns]

In [55]:
df['PREDICTION'] = clf.predict(df[X_train.columns])

In [56]:
print(classification_report(df['Cluster'], df['PREDICTION']))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85997
           1       0.99      0.99      0.99      1062
           2       0.99      0.99      0.99     20461
           3       0.99      0.99      0.99     15362

    accuracy                           1.00    122882
   macro avg       0.99      0.99      0.99    122882
weighted avg       1.00      1.00      1.00    122882



In [57]:
from snowflake.snowpark import Session
import warnings; warnings.simplefilter('ignore')
import configparser

In [58]:
#Import all snowflake connection details from template variables.
db_user = 'MANISH'
db_password = 'Password@2023'
db_account = 'ug94937.us-east4.gcp'
db_database =  'FDC_Insurance'
db_role = 'MANISH'
db_warehouse = 'FOSFOR_SOLUTIONS_WH'
db_schema = 'INS_CUST_SEGMT_SCHEMA'

In [59]:
from snowflake.snowpark.session import Session
connection_params = {
    'user': db_user,
    'password': db_password,
    'account': db_account,
    'warehouse': db_warehouse,
    'database': db_database,
    'schema': db_schema,
    'role': db_role
}
session1 = Session.builder.configs(connection_params).create()

In [60]:
df.shape

(122882, 30)

In [61]:
df_train = df.head(80000)
df_test = df.tail(40000)

In [ ]:
df_train_sf=session1.createDataFrame(
        df_train.values.tolist(),
        schema=df_train.columns.tolist())
df_train_sf.write.mode("overwrite").save_as_table("FDC_Insurance.INS_CUST_SEGMT_SCHEMA.ATM_TRANSACTION_TRAIN_OUTPUT")

In [ ]:
df_test_sf=session1.createDataFrame(
        df_test.values.tolist(),
        schema=df_test.columns.tolist())
df_test_sf.write.mode("overwrite").save_as_table("FDC_Insurance.INS_CUST_SEGMT_SCHEMA.ATM_TRANSACTION_TEST_OUTPUT")