# Use Customer_Segmentation Notebook Template

In [1]:
import numpy as np # linear algebra
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

Matplotlib created a temporary cache directory at /tmp/matplotlib-cjiq6pu5 because the default path (/home/mosaic-ai/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


# Read the intermeditary output of K-Means clustering Model Building Notebooks for model training and registration

In [2]:
df = pd.read_csv('/data/Output/kmeans_clustered_customer_Data.csv')

In [3]:
df.shape

(122882, 29)

In [4]:
df.tail()

CUSTOMER_ID        DATE  AGE     SEX  \
122877  3a7ce3d5-0f4b-4575-badc-3553f5440c92  2023-05-01   32    MALE   
122878  e2a8f308-57eb-4f55-bc13-399378f246d3  2022-12-01   27    MALE   
122879  599c0e61-9bbc-4e14-bbfd-b07f5a398669  2022-12-01   33  FEMALE   
122880  77298902-f899-4c3e-9104-06d1736fb089  2023-06-01   33  FEMALE   
122881  cd75294e-c31f-41b3-b78c-1d3e7322ddcf  2022-12-01   44  FEMALE   

       EDUCATION_LEVEL EMPLOYMENT_STATUS      HOBBIES MARITAL_STATUS  \
122877     High School        Unemployed      reading         Single   
122878             PhD        Unemployed      camping         Single   
122879     High School        Unemployed  video-games         Single   
122880         College        Unemployed   basketball         Single   
122881     High School          Employed     exercise        Married   

            DEPENDENTS REGISTRATION_DATE  ... INSTALLMENTS_PURCHASES  \
122877   One Dependent        2020-03-12  ...              339.07230   
122878   One Dependent        2009-05-12  ...              482.58685   
122879   One Dependent        2007-02-12  ...                0.00000   
122880   One Dependent        2001-02-12  ...                0.00000   
122881  Two Dependents        2001-02-12  ...                0.00000   

        PURCHASES_FREQUENCY ONEOFF_PURCHASES_FREQUENCY  \
122877            Very high                        Low   
122878            Very high                   Very low   
122879             Very low                   Very low   
122880             Very low                   Very low   
122881             Very low                   Very low   

        PURCHASES_INSTALLMENTS_FREQUENCY  PURCHASES_TRX     PAYMENTS  \
122877                         Very high          21.20   273.352691   
122878                         Very high          25.92   474.722440   
122879                          Very low           0.00   568.542708   
122880                          Very low           0.00   517.588408   
122881                          Very low           0.00  1029.696570   

        MINIMUM_PAYMENTS  PRC_FULL_PAYMENT  Cluster           Cluster_Type  
122877        242.288921               0.0        0  Conservative Spenders  
122878        165.534652               0.0        0  Conservative Spenders  
122879        549.300475               0.0        0  Conservative Spenders  
122880        544.214360               0.0        0  Conservative Spenders  
122881       1552.899035               0.0        2     Cash Advance Users  

[5 rows x 29 columns]

In [5]:
to_drop = ['CUSTOMER_ID','DATE','AGE','SEX','EDUCATION_LEVEL','EMPLOYMENT_STATUS','HOBBIES','MARITAL_STATUS','BANK_ACCOUNT_TYPE',
 'DEPENDENTS','REGISTRATION_DATE','PURCHASES_FREQUENCY','ONEOFF_PURCHASES_FREQUENCY','PURCHASES_INSTALLMENTS_FREQUENCY','BALANCE_FREQUENCY','Cluster_Type']

In [6]:
df.drop(to_drop, axis= 1, inplace= True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122882 entries, 0 to 122881
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   BALANCE                 122882 non-null  float64
 1   CREDIT_LIMIT            122882 non-null  float64
 2   CASH_ADVANCE            122882 non-null  float64
 3   CASH_ADVANCE_FREQUENCY  122882 non-null  float64
 4   CASH_ADVANCE_TRX        122882 non-null  float64
 5   PURCHASES               122882 non-null  float64
 6   ONEOFF_PURCHASES        122882 non-null  float64
 7   INSTALLMENTS_PURCHASES  122882 non-null  float64
 8   PURCHASES_TRX           122882 non-null  float64
 9   PAYMENTS                122882 non-null  float64
 10  MINIMUM_PAYMENTS        122882 non-null  float64
 11  PRC_FULL_PAYMENT        122882 non-null  float64
 12  Cluster                 122882 non-null  int64  
dtypes: float64(12), int64(1)
memory usage: 12.2 MB


In [9]:
X = df.drop(['Cluster'],axis = 1 )
y = df[['Cluster']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state = 101)

In [10]:
X_train.shape, X_test.shape

((86017, 12), (36865, 12))

# Decision Tree Classifier

In [11]:
#Training our algorithm
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
clf_prediction = clf.predict(X_test)

In [12]:
#Checking our prediction accuracy score
print(confusion_matrix(y_test, clf_prediction))

[[25607     0   135   122]
 [    0   311     0    10]
 [  111     0  5939    13]
 [  153     7    17  4440]]


In [13]:
print(classification_report(y_test, clf_prediction))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     25864
           1       0.98      0.97      0.97       321
           2       0.98      0.98      0.98      6063
           3       0.97      0.96      0.97      4617

    accuracy                           0.98     36865
   macro avg       0.98      0.98      0.98     36865
weighted avg       0.98      0.98      0.98     36865



In [15]:
clf.feature_importances_

array([0.08022857, 0.03860619, 0.28716542, 0.03354425, 0.10457005,
       0.34349568, 0.00607342, 0.01425587, 0.04124153, 0.02526535,
       0.01268816, 0.01286551])

In [17]:
pd.Series(clf.feature_importances_,index=X_train.columns).sort_values(ascending=False)

PURCHASES                 0.343496
CASH_ADVANCE              0.287165
CASH_ADVANCE_TRX          0.104570
BALANCE                   0.080229
PURCHASES_TRX             0.041242
CREDIT_LIMIT              0.038606
CASH_ADVANCE_FREQUENCY    0.033544
PAYMENTS                  0.025265
INSTALLMENTS_PURCHASES    0.014256
PRC_FULL_PAYMENT          0.012866
MINIMUM_PAYMENTS          0.012688
ONEOFF_PURCHASES          0.006073
dtype: float64

## We achieve 98% accuracy at predicting potiential new customers behavior

In [14]:
from fosforml import *
from fosforml.constants import MLModelFlavours
import requests

In [27]:
payload_dict = X_train.iloc[0].to_dict()

In [28]:
payload_dict

{'BALANCE': 2378.1156415200003,
 'CREDIT_LIMIT': 5640.0,
 'CASH_ADVANCE': 306.9114516,
 'CASH_ADVANCE_FREQUENCY': 0.08749965,
 'CASH_ADVANCE_TRX': 1.035,
 'PURCHASES': 2515.24,
 'ONEOFF_PURCHASES': 2719.5,
 'INSTALLMENTS_PURCHASES': 184.44,
 'PURCHASES_TRX': 9.81,
 'PAYMENTS': 674.70383367,
 'MINIMUM_PAYMENTS': 736.03712752,
 'PRC_FULL_PAYMENT': 0.0}

# Sample Model Payload

In [29]:
print ('{ "payload": ', payload_dict, "}")

{ "payload":  {'BALANCE': 2378.1156415200003, 'CREDIT_LIMIT': 5640.0, 'CASH_ADVANCE': 306.9114516, 'CASH_ADVANCE_FREQUENCY': 0.08749965, 'CASH_ADVANCE_TRX': 1.035, 'PURCHASES': 2515.24, 'ONEOFF_PURCHASES': 2719.5, 'INSTALLMENTS_PURCHASES': 184.44, 'PURCHASES_TRX': 9.81, 'PAYMENTS': 674.70383367, 'MINIMUM_PAYMENTS': 736.03712752, 'PRC_FULL_PAYMENT': 0.0} }


# Define a Score function

In [35]:
@scoring_func
def score(model, request):
    payload_dict = request.json["payload"]
    df = pd.DataFrame(payload_dict,index=[0])
    output = model.predict(df)
    
    if output == 0:
        return ['Conservative Spenders']
    elif output == 1:
        return ['High Spender Users']
    elif output == 2:
        return ['Cash Advance Users']
    else:
        return ['Active Credit Users']

# Sample Model Inference JSON Request

In [40]:
payload_dict = X_train.iloc[0].to_dict()
payload_dict

{'BALANCE': 2378.1156415200003,
 'CREDIT_LIMIT': 5640.0,
 'CASH_ADVANCE': 306.9114516,
 'CASH_ADVANCE_FREQUENCY': 0.08749965,
 'CASH_ADVANCE_TRX': 1.035,
 'PURCHASES': 2515.24,
 'ONEOFF_PURCHASES': 2719.5,
 'INSTALLMENTS_PURCHASES': 184.44,
 'PURCHASES_TRX': 9.81,
 'PAYMENTS': 674.70383367,
 'MINIMUM_PAYMENTS': 736.03712752,
 'PRC_FULL_PAYMENT': 0.0}

In [36]:
req = requests.Request()
req.json = {"payload":payload_dict}
#req.json = {"payload":payload}
y_req = req
score(clf, y_req)

['Conservative Spenders']

In [39]:
payload_dict = X_train.iloc[1000].to_dict()
payload_dict

{'BALANCE': 2161.67703016,
 'CREDIT_LIMIT': 2760.0,
 'CASH_ADVANCE': 7399.04709474,
 'CASH_ADVANCE_FREQUENCY': 0.35999964,
 'CASH_ADVANCE_TRX': 8.64,
 'PURCHASES': 0.0,
 'ONEOFF_PURCHASES': 0.0,
 'INSTALLMENTS_PURCHASES': 0.0,
 'PURCHASES_TRX': 0.0,
 'PAYMENTS': 7500.34928286,
 'MINIMUM_PAYMENTS': 839.24561325,
 'PRC_FULL_PAYMENT': 0.17666702}

In [38]:
req = requests.Request()
req.json = {"payload":payload_dict}
#req.json = {"payload":payload}
y_req = req
score(clf, y_req)

['Cash Advance Users']

# Model registration Code

In [43]:
## registering the model in Fosfor.
model_reg = register_model(clf,
               score, 
               name="Customer_Segmentation_Dtree_Cluster_Classifier", 
               description="Customer_Segmentation_Dtree_Cluster_Classifier",
               flavour=MLModelFlavours.sklearn,
               model_type="classification",
               init_script="\\n pip install fosforml \\n pip install fosforio[snowflake] \\n pip install seaborn \\n pip install snowflake-connector-python[pandas]",
               y_true=y_test,
               y_pred=clf_prediction,
               prob=clf_prediction,
               features=X_train.columns,
               input_type="json", 
               explain_ai=True,
               x_train=X_train, 
               x_test=X_test, 
               y_train=y_train,
               y_test=y_test,
               feature_names=X_train.columns.tolist(),
               original_features=X_train.columns.tolist(),
               feature_ids=X_train.columns,
               kyd=True, kyd_score = True)

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


# Another Version

In [45]:
clf_prediction = clf.predict(X_train)

In [46]:
## registering the model in Fosfor.
model_reg = register_model(clf,
               score, 
               name="Customer_Segmentation_Dtree_Cluster_Classifier", 
               description="Customer_Segmentation_Dtree_Cluster_Classifier",
               flavour=MLModelFlavours.sklearn,
               model_type="classification",
               init_script="\\n pip install fosforml \\n pip install fosforio[snowflake] \\n pip install seaborn \\n pip install snowflake-connector-python[pandas]",
               y_true=y_train,
               y_pred=clf_prediction,
               prob=clf_prediction,
               features=X_train.columns,
               input_type="json", 
               explain_ai=True,
               x_train=X_test, 
               x_test=X_train, 
               y_train=y_test,
               y_test=y_train,
               feature_names=X_train.columns.tolist(),
               original_features=X_train.columns.tolist(),
               feature_ids=X_train.columns,
               kyd=True, kyd_score = True)

Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%
